In [3]:
import torch 

x = torch.randn(1,3, 5)

In [68]:
pred = torch.randn(500, 1, 11)
s = torch.randint(0,2,(500,))
display(s.sum())
s = s.view(-1, 1, 1)
s = torch.squeeze(s)
b = s == 1
pred = pred[b]
display(pred)
display(pred.shape)

tensor(273)

tensor([[[-0.1123, -0.2205,  1.8428,  ...,  0.2003,  0.8074,  0.9903]],

        [[-0.2923, -1.9020, -0.7646,  ..., -0.6766,  0.0141,  0.4463]],

        [[-0.6164, -1.1524, -0.9401,  ..., -1.6328, -0.4651, -0.3668]],

        ...,

        [[-0.2307, -1.8026,  0.0791,  ...,  0.6982, -1.5687, -1.8555]],

        [[-1.7656, -0.3165,  0.1590,  ...,  0.6107,  2.0839, -0.5763]],

        [[-0.5494,  1.9790,  0.0045,  ...,  1.8940, -0.9832, -1.4182]]])

torch.Size([273, 1, 11])

In [66]:
for i in range(pred.shape[0]):
    v = pred[i][0]
    is_zero = len(torch.nonzero(v)) == 0
    if is_zero:
        print(f'tensor at index {i} is all 0')

In [70]:
x = torch.randn(11)
y = torch.randn(11)
display(x)
display(y)

tensor([ 7.2653e-04,  1.3560e+00, -1.4563e+00, -1.4381e+00,  9.9402e-01,
         4.1003e-01,  6.9461e-01,  7.0060e-01, -1.3364e+00, -6.7760e-02,
         1.5448e-01])

tensor([ 0.2895,  0.8692, -0.2492,  0.3074, -1.9362, -1.4238, -0.4139,  1.1702,
        -0.1952, -0.2009, -1.6811])

In [71]:
diff = x - y
display(diff)

tensor([-0.2888,  0.4868, -1.2071, -1.7455,  2.9302,  1.8338,  1.1085, -0.4696,
        -1.1412,  0.1332,  1.8356])

In [72]:
square = diff **2
display(square)

tensor([0.0834, 0.2370, 1.4571, 3.0467, 8.5863, 3.3630, 1.2287, 0.2205, 1.3024,
        0.0177, 3.3694])

In [208]:
pred = torch.randint(-100, 100, (1, 1, 11), dtype=torch.float).to(1)
targ = torch.randint(-100, 100, (1, 1, 11), dtype=torch.float).to(1)

display(pred[:5])
display(targ[:5])

tensor([[[ 27.,  77.,  80.,  -3.,   4.,  44.,  88., -91.,  40.,  34.,   0.]]],
       device='cuda:1')

tensor([[[  9.,   1., -95.,  57., -55., -17.,  36.,  75.,  59.,  73.,  54.]]],
       device='cuda:1')

In [212]:
display((-57 -14)**2)
display((65 -93)**2)
display((48 -72)**2)
display((-9 +92)**2)
    

5041

784

576

6889

In [213]:
loss = torch.nn.MSELoss()

output = loss(pred, targ)
display(output)

tensor(7507.7275, device='cuda:1')

In [214]:
def loss_index(pred, targ, start, end):
    p = pred[:, :, start:end]
    t = targ[:, :, start:end]
    loss = torch.nn.MSELoss()
    output = loss(p, t)
    return output

In [215]:
a = loss_index(pred, targ, 0, 1)
display(a)

b = loss_index(pred, targ, 1, 2)
display(b)

c = loss_index(pred, targ, 2, 3)
display(c)

d = loss_index(pred, targ, 3, 4)
display(d)

e = loss_index(pred, targ, 4, 11)
display(e)

final = (a + b + c + d + e *7) / 11
print('final output')
print(final)

tensor(324., device='cuda:1')

tensor(5776., device='cuda:1')

tensor(30625., device='cuda:1')

tensor(3600., device='cuda:1')

tensor(6037.1431, device='cuda:1')

final output
tensor(7507.7275, device='cuda:1')


In [180]:
s = torch.Tensor(500)
s = s.fill_(0)
b = s == 1
b
byte = b.byte()
display(byte)
display(byte.any())

all_false = byte.any().item() == 0 
print(all_false)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

tensor(0, dtype=torch.uint8)

True


In [141]:
mse = torch.sum((pred - targ)**2) * (1/targ.numel())
# mse = torch.sum((pred - targ)**2)

In [142]:
mse

tensor(844.2407, device='cuda:1')

In [7]:
import torch

pe = torch.randn(5, 11)
display(pe)
display(pe[:, 0::2])
display(pe[:, 1::2])

tensor([[-0.2533, -1.1309,  0.3981,  0.3567,  0.3350, -0.5709,  1.3298,  0.9635,
          0.6017,  0.7755,  1.0888],
        [-0.0178, -1.5589,  0.6162, -1.1520, -0.0455, -0.7064, -1.1989,  0.7995,
          0.3436,  1.0281, -0.0675],
        [ 0.3010, -0.1664, -0.8931,  1.3884, -0.9047,  0.3073,  0.9444, -0.2480,
         -0.5690, -0.9077,  0.0296],
        [-0.9615, -0.4419,  2.4193, -0.3976, -0.6639,  2.8166, -0.6819,  0.2191,
         -0.0337,  1.5510,  0.7961],
        [-0.8296, -2.1406, -1.2744, -1.2556,  0.8849,  0.4220, -2.6180, -0.4671,
         -1.6946, -0.2943,  1.9246]])

tensor([[-0.2533,  0.3981,  0.3350,  1.3298,  0.6017,  1.0888],
        [-0.0178,  0.6162, -0.0455, -1.1989,  0.3436, -0.0675],
        [ 0.3010, -0.8931, -0.9047,  0.9444, -0.5690,  0.0296],
        [-0.9615,  2.4193, -0.6639, -0.6819, -0.0337,  0.7961],
        [-0.8296, -1.2744,  0.8849, -2.6180, -1.6946,  1.9246]])

tensor([[-1.1309,  0.3567, -0.5709,  0.9635,  0.7755],
        [-1.5589, -1.1520, -0.7064,  0.7995,  1.0281],
        [-0.1664,  1.3884,  0.3073, -0.2480, -0.9077],
        [-0.4419, -0.3976,  2.8166,  0.2191,  1.5510],
        [-2.1406, -1.2556,  0.4220, -0.4671, -0.2943]])

In [8]:
position = torch.arange(0, 5, dtype=torch.float)
display(position)

tensor([0., 1., 2., 3., 4.])

In [9]:
display(position.unsqueeze(1))

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [18]:
display(torch.arange(0, max_len))

tensor([0, 1, 2, 3, 4])

In [22]:
import math

max_len = 5
d_model = 11

pe = torch.zeros(max_len, d_model)
position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
display(torch.arange(0, d_model,2).float())
display(position)
display(position[:-1])
display(div_term)
display(div_term[:-1])
display(position*div_term)
pe[:, 0::2] = torch.sin(position * div_term)
if d_model % 2 != 0:
    div_term = div_term[:-1]
    print('even numbered input size')
pe[:, 1::2] = torch.cos(position * div_term)
pe = pe.unsqueeze(0).transpose(0, 1)
# self.register_buffer('pe', pe)

tensor([ 0.,  2.,  4.,  6.,  8., 10.])

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

tensor([[0.],
        [1.],
        [2.],
        [3.]])

tensor([1.0000e+00, 1.8738e-01, 3.5112e-02, 6.5793e-03, 1.2328e-03, 2.3101e-04])

tensor([1.0000, 0.1874, 0.0351, 0.0066, 0.0012])

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.8738e-01, 3.5112e-02, 6.5793e-03, 1.2328e-03, 2.3101e-04],
        [2.0000e+00, 3.7476e-01, 7.0224e-02, 1.3159e-02, 2.4657e-03, 4.6203e-04],
        [3.0000e+00, 5.6215e-01, 1.0534e-01, 1.9738e-02, 3.6985e-03, 6.9304e-04],
        [4.0000e+00, 7.4953e-01, 1.4045e-01, 2.6317e-02, 4.9314e-03, 9.2405e-04]])

even numbered input size
